"""Add resolved column to ContactSubmission

Revision ID: 252ae6bda579
Revises: 
Create Date: 2024-12-25 17:53:38.592194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252ae6bda579'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submission', schema=None) as batch_op:
        batch_op.drop_column('resolved')

    # ### end Alembic commands ###
